version: '3'

services:
  machine1:
    networks:
      - casca
    build: .
    command: "python3 main.py"
    restart: always
    privileged: true

  machine2:
    networks:
      - casca
    build: .
    command: "python3 main.py"
    restart: always
    privileged: true

networks:
  casca:
    external: false
    name: casca
      